name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables..."
          echo "VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}"
          echo "VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}"
          echo "VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}"
          echo "OPENWEATHER_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENWEATHER_API_KEY}}"
          echo "NEWS_API_KEY: ${{ secrets.NEXT_PUBLIC_NEWS_API_KEY}}"
          echo "ALPHA_VANTAGE_API_KEY: ${{ secrets.NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY}}"

      - name: Pull Vercel Environment Information
        run: |
          echo "Pulling Vercel environment information..."
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          echo "Environment pull completed"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: |
          echo "Starting build process..."
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          echo "Build completed"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          NEXT_PUBLIC_OPENWEATHER_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENWEATHER_API_KEY }}
          NEXT_PUBLIC_NEWS_API_KEY: ${{ secrets.NEXT_PUBLIC_NEWS_API_KEY }}
          NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY: ${{ secrets.NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          echo "Starting deployment..."
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          echo "Deployment completed"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
